/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modificado para aceptar animaciones dinámicas
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { Group } from 'three'

interface FoxProps extends React.PropsWithChildren {
  animationName?: string
  isAnimating?: boolean
  [key: string]: any
}

export function Fox({
  animationName,
  isAnimating = false,
  ...props
}: FoxProps) {
  const group = useRef<Group>(null)
  const { nodes, materials, animations } = useGLTF(
    '/models/FoxPreview.glb',
  ) as any
  const { actions, names: animationNames } = useAnimations(
    animations,
    group as any,
  )

  // Auto-play primera animación disponible o la especificada
  useEffect(() => {
    if (!actions) return

    const CROSSFADE_DURATION = 0.5

    // Si llegó un nombre de animación específica, hacer crossfade a esa
    if (
      animationName &&
      animationNames.includes(animationName) &&
      isAnimating
    ) {
      const targetAction = actions[animationName]
      if (targetAction) {
        // Crossfade suave desde animación actual
        Object.entries(actions).forEach(([name, action]: [string, any]) => {
          if (name !== animationName && action && action.isRunning?.()) {
            targetAction.reset()
            action.crossFadeTo(targetAction, CROSSFADE_DURATION, true)
            targetAction.play()
          }
        })
        // Si no hay otra animación en progreso, solo play
        if (!Object.values(actions).some((a: any) => a?.isRunning?.())) {
          targetAction.reset()
          targetAction.play()
        }
        console.log(`▶ Playing animation: ${animationName}`)
      }
    } else if (!isAnimating) {
      // Volver a Idle con crossfade suave
      const firstAnimName = animationNames?.[0]
      if (firstAnimName && actions[firstAnimName]) {
        const idleAction = actions[firstAnimName]
        // Crossfade desde cualquier animación actual
        Object.entries(actions).forEach(([name, action]: [string, any]) => {
          if (name !== firstAnimName && action && action.isRunning?.()) {
            action.crossFadeTo(idleAction, CROSSFADE_DURATION, true)
            idleAction.play()
          }
        })
        // Si ninguna está en progreso, asegurar que idle esté playing
        if (!Object.values(actions).some((a: any) => a?.isRunning?.())) {
          idleAction.reset()
          idleAction.play()
        }
        console.log(`▶ Returning to idle animation: ${firstAnimName}`)
      }
    }
  }, [animationName, isAnimating, actions, animationNames])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={(nodes.Cylinder as any)?.geometry}
          material={materials['Material.005']}
        />
        <group name="metarig">
          <group name="Cube">
            <skinnedMesh
              name="Cube_1"
              geometry={(nodes.Cube_1 as any)?.geometry}
              material={materials.Material}
              skeleton={(nodes.Cube_1 as any)?.skeleton}
            />
            <skinnedMesh
              name="Cube_2"
              geometry={(nodes.Cube_2 as any)?.geometry}
              material={materials['Material.001']}
              skeleton={(nodes.Cube_2 as any)?.skeleton}
            />
            <skinnedMesh
              name="Cube_3"
              geometry={(nodes.Cube_3 as any)?.geometry}
              material={materials['Material.002']}
              skeleton={(nodes.Cube_3 as any)?.skeleton}
            />
            <skinnedMesh
              name="Cube_4"
              geometry={(nodes.Cube_4 as any)?.geometry}
              material={materials['Material.004']}
              skeleton={(nodes.Cube_4 as any)?.skeleton}
            />
          </group>
          <primitive object={nodes.spine} />
          <primitive object={nodes.neutral_bone} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/FoxPreview.glb')
