/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modificado para aceptar animaciones dinámicas de la gaviota (Seagull)
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { Group } from 'three'

interface SeagullProps {
  animationName?: string
  isAnimating?: boolean
  [key: string]: any
}

export function Seagull({
  animationName,
  isAnimating = false,
  ...props
}: SeagullProps) {
  const group = useRef<Group>(null)
  
  // Cargamos el modelo que movimos a public/models
  const { nodes, materials, animations } = useGLTF(
    '/models/Seagull.glb',
  ) as any
  
  const { actions, names: animationNames } = useAnimations(
    animations,
    group as any,
  )

  // Console log for debugging available animations in the GLB
  useEffect(() => {
    if (animationNames.length > 0) {
      console.log('🐦 Seagull Animations Available:', animationNames);
    }
  }, [animationNames]);

  // Sincronización de animaciones (Basado en Fox.tsx)
  useEffect(() => {
    if (!actions || animationNames.length === 0) return

    const CROSSFADE_DURATION = 0.5
    
    // Priorizamos la animación solicitada o la primera disponible (Idle general)
    const targetAnim = (animationName && animationNames.includes(animationName)) 
      ? animationName 
      : animationNames[0]

    const targetAction = actions[targetAnim]
    
    if (targetAction) {
      // Fade out de las demás animaciones
      Object.values(actions).forEach((action: any) => {
        if (action && action.isRunning() && action !== targetAction) {
          action.fadeOut(CROSSFADE_DURATION)
        }
      })

      // Activar la nueva
      targetAction.reset().fadeIn(CROSSFADE_DURATION).play()
      
      // Si es un "Speak" o "Action", le ponemos un loop simple o pingpong si existe
      // Pero por ahora, que ruede lo que traiga el target
    }

    return () => {
      if (targetAction) targetAction.fadeOut(CROSSFADE_DURATION)
    }
  }, [animationName, actions, animationNames])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0, 0]} rotation={[0, 0, 0]}>
          <skinnedMesh
            name="Seagul"
            geometry={(nodes.Seagul as any).geometry}
            material={materials['Material.001']}
            skeleton={(nodes.Seagul as any).skeleton}
            castShadow
            receiveShadow
          />
          <primitive object={nodes['Bn-Back-1']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Seagull.glb')
